version: "3"
services:
  dynalist-automator:
    image: node:alpine
    restart: on-failure
    environment:
      - DYNALIST_TOKEN
    volumes:
      - .:/app
      - ./tmp:/tmp
    command: node /app/dist/index.js /app/config.prod.js
